import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/language_provider.dart';

String tr(WidgetRef ref, String key) {
  try {
    final lang = ref.watch(languageProvider);
    return _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
  } catch (e) {
    // Return fallback if ref is disposed or watch fails
    return _translations['en']?[key] ?? key;
  }
}

const Map<String, Map<String, String>> _translations = {
  'en': {
    'dashboard': 'Dashboard',
    'catalogs': 'Catalogs',
    'customers': 'Customers',
    'sales': 'Sales',
    'expenses': 'Expenses',
    'finance': 'Finance',
    'financial_health': 'Financial Health',
    'total_revenue': 'Total Revenue',
    'stock_cost': 'Stock Cost',
    'available_profit': 'Available Profit',
    'net_profit': 'Net Profit',
    'salary_from_profit': 'Salary from Profit',
    'business_from_profit': 'Business from Profit',
    'capital_pool': 'Capital Pool',
    'cash_capital': 'Cash Capital',
    'assets_capital': 'Assets Capital',
    'stock_deployed': 'Stock Deployed',
    'recovered_from_sales': 'Recovered from Sales',
    'remaining_to_recover': 'Remaining to Recover',
    'capital_energy': 'Capital Energy',
    'capital_energy_desc': 'This bar shows how much of your initial capital has been recovered by sales. Profit only starts after capital is fully recovered.',
    'no_sales_yet': 'No sales yet',
    'tap_to_add_sale': 'Tap + to record your first sale',
    'expense_details': 'Expense Details',
    'product': 'Product',
    'quantity': 'Quantity',
    'sale': 'Sale',
    'unit_sales': 'sales',
    'second_hand': 'Second-hand',
    'new_condition': 'New',
    'not_specified': 'Not specified',
    'dress': 'Dress',
    'blouse': 'Blouse',
    'trouser': 'Trouser',
    'set': 'Set',
    'jacket': 'Jacket',
    'skirt': 'Skirt',
    'shirt': 'Shirt',
    'pants': 'Pants',
    'other': 'Other',
    'units': 'units',
    'out_of_stock': 'Out of Stock',
    'no_products_found': 'No products found',
    'add_stock_from_expenses': 'Add stock from expenses to see items here.',
    'stock_level': 'Stock Level',
    'date': 'Date',
    'description': 'Description',
    'condition': 'Condition',
    'no_description_provided': 'No description provided',
    'update_stock_price': 'Update Stock/Price',
    'quick_update': 'Quick Update',
    'selling_price': 'Selling Price',
    'cancel': 'Cancel',
    'save_changes': 'Save Changes',
    'all': 'All',
    'sales_count': 'Sales Count',
    'revenue': 'Revenue',
    'profit': 'Profit',
    'financial_resume': 'Financial Resume',
    'profit_analysis': 'Profit Analysis',
    'operational_expenses': 'Operational Expenses',
    'capital_overview': 'Capital Overview',
    'monthly_weekly_resume': 'Monthly/Weekly Resume',
    'recent_activity': 'Recent Activity',
    'no_activity': 'No Activity',
    'capital_coverage': 'Capital Coverage',
    'recovered': 'Recovered',
    'remaining': 'Remaining',
    'previous_week': 'Previous Week',
    'week_summary': 'Week Summary',
    'online': 'Online',
    'offline_mode': 'Offline Mode',
    'manage_business_data': 'Manage business data',
    'settings': 'Settings',
    'ping_connection': 'Ping Connection',
    'real_time_performance': 'Real-time performance',
    'setup_shop': 'Setup your shop',
    'setup_business_profile': 'Setup your business profile before starting.',
    'initial_capital': 'Initial Capital (XAF)',
    'start_app': 'Start',
    'english': 'English',
    'french': 'French',
    'language': 'Language',
    'exit_app': 'Exit App',
    'are_you_sure_exit': 'Are you sure you want to exit?',
    'exit': 'Exit',
    'pending_deliveries': 'Pending Deliveries',
    'low_stock_items': 'Low Stock Items',
    'restock_suggestion': 'Consider restocking these items soon.',
    'finance_summary': 'Finance Summary',
    'monthly_performance': 'Monthly Performance',
    'expenses_breakdown': 'Expenses Breakdown',
    'this_week_summary': 'This Week Summary',
    'this_week': 'This Week',
    'all_time': 'All Time',
    'profit_distribution': 'Profit Distribution',
    'capital_injections': 'Capital Injections',
    'capital_injection_details': 'Capital Injection Details',
    'delete': 'Delete',
    'weekly_checkup': 'Weekly Checkup',
    'weekly_checkups': 'Weekly Checkups',
    'completed': 'Completed',
    'pending': 'Pending',
    'complete': 'Complete',
    'inject_capital': 'Inject Capital',
    'quick_resume': 'Quick Resume',
    'setup_shop_loading': 'Setting up your shop...',
    'fetching_cloud_data': 'Fetching cloud data',
    'error': 'Error',
    'retry': 'Retry',
    'dark_mode': 'Dark Mode',
    'logout': 'Logout',
    'welcome_corporate_ladies': 'Welcome to Corporate Ladies',
    'filter': 'Filter:',
    'sales_only': 'Sales Only',
    'expenses_only': 'Expenses Only',
    'edit': 'Edit',
    'syncing_data': 'Syncing data...',
    'sync_completed': 'Sync completed successfully!',
    'sync_failed': 'Sync failed',
    'success': 'Success',
    'great': 'Great',
    'no_log_file': 'No log file found.',
    'error_sharing_logs': 'Error sharing logs',
    'save_logs_local': 'Save Logs Locally',
    'save_logs_subtitle': 'Export current application logs to a file',
    'connection_failed': 'Connection Failed',
    'dismiss': 'Dismiss',
    'confirm_full_reset': 'Confirm Full Reset',
    'wipe_data': 'Wipe Data',
    'system_reset_completed': 'System reset completed.',
    'reset_failed': 'Reset failed',
    'new_sale_type': 'New Sale Type',
    'is_this_direct_or_delivery': 'Is this a store sale or delivery?',
    'direct_sale': 'Store Sale',
    'delivery': 'Delivery',
    'no_discount': 'No Discount',
    'enter_discount_amount': 'Enter Discount Amount',
    'discount_amount': 'Discount Amount',
    'inventory_selection': 'Inventory Selection:',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'grand_total': 'Grand Total',
    'confirm_sale': 'Confirm Sale',
    'quick_add_customer': 'Quick Add Customer',
    'save': 'Save',
    'sale_details': 'Sale Details',
    'items': 'Items',
    'confirm_paid': 'Confirm Paid',
    'close': 'Close',
    'edit_sale_date': 'Edit Sale Date',
    'select_date': 'Select Date',
    'select_time': 'Select Time',
    'update_price_and_stock': 'Update Price and Stock',
    'update': 'Update',
    'name': 'Name',
    'phone': 'Phone',
    'notes': 'Notes',
    'optional': 'Optional',
    'stock_quantity': 'Quantity in stock',
    'required': 'Required',
    'delivery_address': 'Delivery Address',
    'category': 'Category',
    'amount': 'Amount',
    'stock_expense': 'Stock Expense',
    'business_expense': 'Business Expense',
    'personal_payout': 'Personal Payout',
    'select_customer': 'Select Customer',
    'profit_payout': 'Profit Payout (as salary)',
    'reinject_capital': 'Reinject as Capital',
    'complete_checkup': 'Complete Checkup',
    'add_new_category': 'Add New Category',
    'are_you_sure_delete': 'Are you sure you want to delete',
    'category_name': 'Category Name',
    'condition_tier': 'Condition Tier',
    'boutique': 'Boutique',
    'are_you_sure_delete_customer': 'Are you sure you want to delete',
    'hide_from_active': 'This will hide them from the active list.',
    'registration_success': 'Registration successful! Please check your email.',
    'sign_in': 'Sign In',
    'forgot_password': 'Forgot password?',
    'development_bypass': 'Guest Mode',
    'register': 'Register',
    'weekly_financial_checkup': 'Weekly Financial Checkup',
    'sunday_reset_desc': 'It\'s Sunday! Time to review your weekly performance.',
    'total_revenue_this_week': 'Total Revenue This Week',
    'total_expenses_this_week': 'Total Expenses This Week',
    'complete_reset': 'Complete Reset',
    'weekly_reports': 'Weekly Reports',
    'performance_metrics': 'Performance Metrics',
    'stock_items': 'Stock Items',
    'category_breakdown': 'Category Breakdown',
    'top_products': 'Top Products',
    'last_week_performance': 'Last Week Performance',
    'no_reports_yet': 'No reports yet',
    'view_all': 'View All',
    'new_delivery_sale': 'New Delivery Sale',
    'direct_store_sale': 'Direct Store Sale',
    'available_products': 'Available Products',
    'in_stock': 'in stock',
    'items_in_cart': 'Items in cart',
    'clear_all': 'Clear All',
    'error_select_customer': 'Please select a customer for this sale',
    'regular_client': 'Regular Client',
    'purchases': 'purchases',
    'one_time_setup_desc': 'This happens only once.',
    'optional_discount': 'Optional Discount',
    'no_expenses_yet': 'No expenses yet',
    'no_expenses_category': 'No expenses in this category',
    'tap_to_add_expense': 'Tap + to add your first expense',
    'select_different_category': 'Select a different category',
    'stock_expense_title': 'Stock Expense',
    'business_expense_title': 'Business Expense',
    'personal_payout_title': 'Personal Payout (Salary)',
    'capital_injection_title': 'Capital Injection',
    'add_expense': 'Add Expense',
    'edit_expense': 'Edit Expense',
    'stock_refill_info': 'Stock refill uses capital.',
    'projected_margin_help': 'Marge projetée = (revente - coût) x quantité',
    'product_names': 'Product Name(s) *',
    'product_names_hint': 'ex: Summer Dress',
    'product_names_helper': 'Enter names separated by commas',
    'garment_category': 'Garment Category *',
    'available_capital': 'Available Capital',
    'capital_pool_help': 'Pool de capital = Injections + Chiffre d\'affaires - Dépenses de stock',
    'purchase_price_unit': 'Purchase Price (unit) *',
    'resale_price_unit': 'Resale Price (unit) *',
    'projected_profit': 'Projected Profit',
    'projected_profit_help': 'Estimated profit if all units are sold.',
    'product_details_label': 'Product Details',
    'resale_price_error': 'Resale price must be higher than purchase price',
    'insufficient_capital': 'Insufficient Capital',
    'product_details': 'Product Details',
    'product_image': 'Product Image',
    'no_image_selected': 'No image selected',
    'upload_image': 'Upload Image',
    'available_stock': 'Available Stock',
    'inventory_management': 'Inventory Management',
    'no_customers_yet': 'No customers yet',
    'add_customer': 'Add Customer',
    'edit_customer': 'Edit Customer',
    'address': 'Address',
    'email': 'Email',
    'business_expenses': 'Business Expenses',
    'payout_exceed_profit': 'Payout cannot exceed available profit',
    'stock_purchased': 'Stock Purchased',
    'sales_revenue': 'Sales Revenue',
    'capital_covered': 'Capital Covered',
    'realized_profit': 'Realized Profit',
    'gross_margin': 'Gross Margin',
    'operating_margin': 'Operating Margin',
    'salary_ratio': 'Salary Ratio',
    'business_cost_ratio': 'Business Cost Ratio',
    'owner_salary': 'Owner Salary',
    'capital_recovered': 'Capital Recovered',
    'capital_energy_help': 'This bar shows recovery of capital.',
    'gross_margin_help': 'Gross margin on sales.',
    'operating_margin_help': 'Net profit after expenses.',
    'salary_ratio_help': 'Part of profit taken as salary.',
    'business_cost_ratio_help': 'Part of revenue going to fixed costs.',
    'capital_covered_help': 'Percentage of stock recovered by sales.',
    'total_capital_injected': 'Total Capital Injected',
    'available_cash_capital': 'Available Cash Capital',
    'time': 'Time',
    'amount_xaf': 'Amount (XAF)',
    'cash_capital_injection': 'Cash Capital Injection',
    'weekly_payout_desc': 'Weekly payout',
    'profile': 'Profile',
    'cloud_sync_data': 'Cloud Sync & Data',
    'manual_data_sync': 'Manual Data Sync',
    'manual_sync_subtitle': 'Sync manually with cloud',
    'check_db_connection': 'Check DB Connection',
    'check_db_subtitle': 'Verify database communication',
    'exports': 'Exports',
    'export_all_data': 'Export All Data',
    'export_all_subtitle': 'Download everything as JSON',
    'inventory_export_csv': 'Inventory Export (CSV)',
    'inventory_export_subtitle': 'Perfect for Excel or Sheets',
    'diagnostics_support': 'Diagnostics & Support',
    'share_error_logs': 'Share Error Logs',
    'share_logs_subtitle': 'Send technical logs to support',
    'wipe_all_data': 'Wipe All Data',
    'wipe_data_subtitle': 'Deletes local and cloud data',
    'app_settings': 'App Settings',
    'sign_out': 'Sign Out',
    'sign_out_subtitle': 'Sign out safely',
    'dark_mode_subtitle': 'Dark theme',
    'light_mode_subtitle': 'Light theme',
    'db_connect_success': 'Database connection successful.',
    'db_schema_tip': 'TIP: Verify Supabase SQL schema.',
    'confirm_reset_desc': 'Action is irreversible.',
    'camera': 'Camera',
    'gallery': 'Gallery',
    'select_image_source': 'Select Image Source',
    'error_picking_image': 'Error picking image',
    'invalid_amount': 'Please enter a valid amount',
    'weekly_reports_history': 'Weekly Reports History',
    'complete_first_checkup_desc': 'Perform your first weekly checkup.',
    'week_end_date': 'Week End Date',
    'summary': 'Summary',
    'connection_error': 'Connection Error',
    'offline_auth_error': 'Device is offline.',
    'continue_offline': 'Continue Offline',
    'purchase_history': 'Purchase History',
    'total_spent': 'Total Spent',
    'suggested_discount': 'Suggested Discount',
    'off_next_purchase': 'off next purchase',
    'loyal_customer_gold': 'Loyal customer',
    'loyal_customer_silver': 'Regular customer',
    'loyal_customer_bronze': 'New regular',
    'no_purchases_yet': 'No purchases yet',
    'january': 'January',
    'february': 'February',
    'march': 'March',
    'april': 'April',
    'may': 'May',
    'june': 'June',
    'july': 'July',
    'august': 'August',
    'september': 'September',
    'october': 'October',
    'november': 'November',
    'december': 'December',
    'capital_pool_desc': 'Total business value.',
    'cash_capital_desc': 'Liquid cash available.',
    'assets_capital_desc': 'Current stock value.',
    'stock_deployed_desc': 'Total amount spent on stock.',
    'sales_count_desc': 'Number of sales recorded.',
    'available_profit_desc': 'Net profit ready for withdrawal.',
    'salary_from_profit_desc': 'Total profit taken as personal income.',
    'revenue_help': 'Total income from paid sales.',
    'stock_cost_help': 'Money spent on inventory.',
    'business_expenses_help': 'Operational costs like transport.',
    'owner_salary_help': 'Total cash withdrawn as profit.',
    'view': 'View',
    'please_wait_initial_sync': 'Please wait while we sync your data for the first time...',
  },
  'fr': {
    'dashboard': 'Tableau de bord',
    'catalogs': 'Catalogues',
    'customers': 'Clients',
    'sales': 'Ventes',
    'expenses': 'Dépenses',
    'finance': 'Finance',
    'financial_health': 'Santé financière',
    'total_revenue': 'Revenu total',
    'stock_cost': 'Coût du stock',
    'available_profit': 'Profit disponible',
    'capital_coverage': 'Couverture du capital',
    'pending_deliveries': 'Livraisons en attente',
    'low_stock_items': 'Stock faible',
    'restock_suggestion': 'Pensez à réapprovisionner ces articles bientôt.',
    'recent_activity': 'Activité récente',
    'no_activity': 'Aucune activité',
    'finance_summary': 'Résumé financier',
    'monthly_performance': 'Performance Mensuelle',
    'capital_energy': 'Énergie du capital',
    'capital_energy_desc': 'Cette barre montre quelle proportion de votre capital initial a été récupérée par les ventes.',
    'no_sales_yet': 'Aucune vente pour le moment',
    'tap_to_add_sale': 'Appuyez sur + pour enregistrer une vente',
    'expense_details': 'Détails de la dépense',
    'product': 'Produit',
    'quantity': 'Quantité',
    'sale': 'Vente',
    'unit_sales': 'ventes',
    'second_hand': 'Friperie',
    'new_condition': 'Neuf',
    'dress': 'Robe',
    'blouse': 'Chemisier',
    'trouser': 'Pantalon',
    'set': 'Ensemble',
    'jacket': 'Veste',
    'skirt': 'Jupe',
    'shirt': 'Chemise',
    'pants': 'Pantalon',
    'other': 'Autre',
    'units': 'unités',
    'out_of_stock': 'RUPTURE DE STOCK',
    'no_products_found': 'Aucun produit trouvé',
    'add_stock_from_expenses': 'Ajoutez du stock depuis les dépenses.',
    'stock_level': 'Niveau de stock',
    'date': 'Date',
    'description': 'Description',
    'condition': 'État',
    'no_description_provided': 'Aucune description fournie',
    'update_stock_price': 'Mise à jour Stock/Prix',
    'quick_update': 'Mise à jour rapide',
    'selling_price': 'Prix de vente',
    'cancel': 'Annuler',
    'save_changes': 'Enregistrer',
    'all': 'Tout',
    'sales_count': 'Nombre de ventes',
    'revenue': 'Revenu',
    'profit': 'Profit',
    'financial_resume': 'Résumé financier',
    'profit_analysis': 'Analyse du profit',
    'operational_expenses': 'Dépenses opérationnelles',
    'capital_overview': 'Aperçu du capital',
    'monthly_weekly_resume': 'Résumé mensuel/hebdomadaire',
    'recovered': 'Récupéré',
    'remaining': 'Restant',
    'previous_week': 'Semaine précédente',
    'week_summary': 'Résumé de la semaine',
    'online': 'En ligne',
    'offline_mode': 'Mode hors ligne',
    'manage_business_data': 'Gérer les données',
    'settings': 'Paramètres',
    'ping_connection': 'Vérifier la connexion',
    'real_time_performance': 'Performance en temps réel',
    'setup_shop': 'Configuration boutique',
    'setup_business_profile': 'Configurez votre profil avant de commencer.',
    'initial_capital': 'Capital initial (XAF)',
    'start_app': 'Démarrer',
    'english': 'Anglais',
    'french': 'Français',
    'language': 'Langue',
    'exit_app': 'Quitter l\'application',
    'are_you_sure_exit': 'Voulez-vous quitter?',
    'exit': 'Quitter',
    'expenses_breakdown': 'Répartition des dépenses',
    'this_week_summary': 'Résumé de la semaine',
    'this_week': 'Cette semaine',
    'all_time': 'Tout le temps',
    'profit_distribution': 'Distribution du profit',
    'capital_injections': 'Injections de capital',
    'capital_injection_details': 'Détails de l\'injection',
    'delete': 'Supprimer',
    'weekly_checkup': 'Contrôle hebdomadaire',
    'weekly_checkups': 'Contrôles hebdomadaires',
    'completed': 'Terminé',
    'pending': 'En attente',
    'complete': 'Terminé',
    'inject_capital': 'Injecter du capital',
    'quick_resume': 'Résumé rapide',
    'setup_shop_loading': 'Configuration en cours...',
    'fetching_cloud_data': 'Récupération des données cloud',
    'error': 'Erreur',
    'retry': 'Réessayer',
    'dark_mode': 'Mode sombre',
    'logout': 'Déconnexion',
    'welcome_corporate_ladies': 'Bienvenue chez Corporate Ladies',
    'filter': 'Filtre:',
    'sales_only': 'Ventes seulement',
    'expenses_only': 'Dépenses seulement',
    'edit': 'Modifier',
    'syncing_data': 'Synchronisation...',
    'sync_completed': 'Synchronisation réussie!',
    'sync_failed': 'Échec synchronisation',
    'success': 'Succès',
    'great': 'Super',
    'no_log_file': 'Aucun fichier de journal.',
    'error_sharing_logs': 'Erreur partage journaux',
    'save_logs_local': 'Enregistrer les journaux localement',
    'save_logs_subtitle': 'Exporter les journaux vers un fichier',
    'connection_failed': 'Échec connexion',
    'dismiss': 'Fermer',
    'confirm_full_reset': 'Confirmer réinitialisation',
    'wipe_data': 'Effacer les données',
    'system_reset_completed': 'Réinitialisation terminée.',
    'reset_failed': 'Échec réinitialisation',
    'new_sale_type': 'Nouveau type de vente',
    'is_this_direct_or_delivery': 'Vente magasin ou livraison?',
    'direct_sale': 'Vente magasin',
    'delivery': 'Livraison',
    'no_discount': 'Pas de remise',
    'enter_discount_amount': 'Entrez le montant de la remise',
    'discount_amount': 'Montant de la remise',
    'inventory_selection': 'Sélection inventaire:',
    'subtotal': 'Sous-total',
    'discount': 'Remise',
    'grand_total': 'Total général',
    'confirm_sale': 'Confirmer la vente',
    'quick_add_customer': 'Ajout rapide client',
    'save': 'Enregistrer',
    'sale_details': 'Détails vente',
    'items': 'Articles',
    'confirm_paid': 'Confirmer payé',
    'close': 'Fermer',
    'edit_sale_date': 'Modifier date vente',
    'select_date': 'Sélectionner date',
    'select_time': 'Sélectionner heure',
    'update_price_and_stock': 'Mise à jour Prix/Stock',
    'update': 'Mettre à jour',
    'name': 'Nom',
    'phone': 'Téléphone',
    'notes': 'Notes',
    'optional': 'Optionnel',
    'stock_quantity': 'Quantité en stock',
    'required': 'Obligatoire',
    'delivery_address': 'Adresse livraison',
    'category': 'Catégorie',
    'amount': 'Montant',
    'stock_expense': 'Dépense stock',
    'business_expense': 'Dépense pro',
    'personal_payout': 'Versement personnel',
    'select_customer': 'Choisir client',
    'profit_payout': 'Versement profit (salaire)',
    'reinject_capital': 'Réinjecter capital',
    'complete_checkup': 'Terminer le contrôle',
    'add_new_category': 'Ajouter catégorie',
    'are_you_sure_delete': 'Voulez-vous supprimer',
    'category_name': 'Nom catégorie',
    'condition_tier': 'Niveau condition',
    'boutique': 'Boutique',
    'are_you_sure_delete_customer': 'Voulez-vous supprimer',
    'hide_from_active': 'Cela le cachera de la liste.',
    'registration_success': 'Inscription réussie ! Vérifiez vos emails.',
    'sign_in': 'Connexion',
    'forgot_password': 'Mot de passe oublié?',
    'development_bypass': 'Mode invité',
    'register': 'S\'inscrire',
    'weekly_financial_checkup': 'Contrôle Financier Hebdo',
    'sunday_reset_desc': 'C\'est dimanche ! Revoyez vos performances.',
    'total_revenue_this_week': 'Revenu de la semaine',
    'total_expenses_this_week': 'Dépenses de la semaine',
    'complete_reset': 'Réinitialisation complète',
    'weekly_reports': 'Rapports hebdomadaires',
    'performance_metrics': 'Mesures de performance',
    'stock_items': 'Articles en stock',
    'category_breakdown': 'Répartition catégorie',
    'top_products': 'Meilleurs produits',
    'last_week_performance': 'Performance semaine passée',
    'no_reports_yet': 'Aucun rapport',
    'view_all': 'Voir tout',
    'new_delivery_sale': 'Nouvelle livraison',
    'direct_store_sale': 'Vente directe',
    'available_products': 'Produits dispos',
    'in_stock': 'en stock',
    'items_in_cart': 'Articles au panier',
    'clear_all': 'Tout effacer',
    'error_select_customer': 'Veuillez choisir un client',
    'regular_client': 'Client régulier',
    'purchases': 'achats',
    'one_time_setup_desc': 'Ceci arrive une seule fois.',
    'optional_discount': 'Remise facultative',
    'no_expenses_yet': 'Aucune dépense',
    'no_expenses_category': 'Aucune dépense dans cette catégorie',
    'tap_to_add_expense': 'Appuyez sur + pour ajouter',
    'select_different_category': 'Choisir une autre catégorie',
    'stock_expense_title': 'Dépense de Stock',
    'business_expense_title': 'Dépense Pro',
    'personal_payout_title': 'Versement Personnel',
    'capital_injection_title': 'Injection de Capital',
    'add_expense': 'Ajouter dépense',
    'edit_expense': 'Modifier dépense',
    'stock_refill_info': 'Le stock utilise le capital.',
    'projected_margin_help': 'Marge estimée sur les ventes.',
    'product_names': 'Nom(s) produit *',
    'product_names_hint': 'ex: Robe d\'été',
    'product_names_helper': 'Séparez les noms par des virgules',
    'garment_category': 'Catégorie vêtement *',
    'available_capital': 'Capital disponible',
    'capital_pool_help': 'Total cash + valeur stock.',
    'purchase_price_unit': 'Prix d\'achat (unité) *',
    'resale_price_unit': 'Prix revente (unité) *',
    'projected_profit': 'Profit projeté',
    'projected_profit_help': 'Profit si tout est vendu.',
    'product_details_label': 'Détails produit',
    'resale_price_error': 'Le prix de revente doit être > achat',
    'insufficient_capital': 'Capital insuffisant',
    'product_details': 'Détails du produit',
    'product_image': 'Image du produit',
    'no_image_selected': 'Aucune image sélectionnée',
    'upload_image': 'Télécharger une image',
    'available_stock': 'Stock disponible',
    'inventory_management': 'Gestion inventaire',
    'no_customers_yet': 'Aucun client',
    'tap_to_add_customer': 'Appuyez sur + pour ajouter',
    'add_customer': 'Ajouter client',
    'edit_customer': 'Modifier client',
    'address': 'Adresse',
    'email': 'Email',
    'business_expenses': 'Dépenses pro',
    'payout_exceed_profit': 'Le versement > profit disponible',
    'stock_purchased': 'Stock acheté',
    'sales_revenue': 'Revenu ventes',
    'capital_covered': 'Capital récupéré',
    'realized_profit': 'Profit réalisé',
    'gross_margin': 'Marge brute',
    'operating_margin': 'Marge opérationnelle',
    'salary_ratio': 'Ratio salaire',
    'business_cost_ratio': 'Ratio frais fixes',
    'owner_salary': 'Salaire propriétaire',
    'capital_recovered': 'Capital récupéré',
    'capital_energy_help': 'Récupération du capital initial.',
    'gross_margin_help': 'Marge sur ventes.',
    'operating_margin_help': 'Profit après toutes dépenses.',
    'salary_ratio_help': 'Part du profit en salaire.',
    'business_cost_ratio_help': 'Part des frais fixes.',
    'capital_covered_help': 'Stock récupéré par les ventes.',
    'total_capital_injected': 'Capital injecté',
    'available_cash_capital': 'Cash disponible',
    'time': 'Heure',
    'amount_xaf': 'Montant (XAF)',
    'cash_capital_injection': 'Injection cash',
    'weekly_payout_desc': 'Versement hebdo',
    'profile': 'Profil',
    'cloud_sync_data': 'Sync Cloud & Données',
    'manual_data_sync': 'Sync manuelle',
    'manual_sync_subtitle': 'Synchroniser avec le cloud',
    'check_db_connection': 'Vérifier connexion',
    'check_db_subtitle': 'Vérifier la base de données',
    'exports': 'Exportations',
    'export_all_data': 'Exporter données',
    'export_all_subtitle': 'Télécharger au format JSON',
    'inventory_export_csv': 'Export inventaire (CSV)',
    'inventory_export_subtitle': 'Format Excel / Sheets',
    'diagnostics_support': 'Diagnostics & Support',
    'share_error_logs': 'Partager journaux',
    'share_logs_subtitle': 'Envoyer les logs au support',
    'wipe_all_data': 'Effacer données',
    'wipe_data_subtitle': 'Supprime local & cloud',
    'app_settings': 'Paramètres',
    'sign_out': 'Déconnexion',
    'sign_out_subtitle': 'Se déconnecter',
    'dark_mode_subtitle': 'Thème sombre',
    'light_mode_subtitle': 'Thème clair',
    'db_connect_success': 'Connexion réussie.',
    'db_schema_tip': 'CONSEIL : Vérifiez le schéma SQL.',
    'confirm_reset_desc': 'Action irréversible.',
    'camera': 'Appareil photo',
    'gallery': 'Galerie',
    'select_image_source': 'Choisir source',
    'error_picking_image': 'Erreur sélection',
    'invalid_amount': 'Montant invalide',
    'weekly_reports_history': 'Historique hebdo',
    'complete_first_checkup_desc': 'Faites votre premier contrôle.',
    'week_end_date': 'Date de fin',
    'summary': 'Résumé',
    'connection_error': 'Erreur connexion',
    'offline_auth_error': 'Appareil hors ligne.',
    'continue_offline': 'Continuer hors ligne',
    'purchase_history': 'Historique d\'achat',
    'total_spent': 'Total acheté',
    'suggested_discount': 'Remise suggérée',
    'off_next_purchase': 'de remise',
    'loyal_customer_gold': 'Client fidèle',
    'loyal_customer_silver': 'Client régulier',
    'loyal_customer_bronze': 'Nouveau régulier',
    'no_purchases_yet': 'Aucun achat',
    'january': 'Janvier',
    'february': 'Février',
    'march': 'Mars',
    'april': 'Avril',
    'may': 'Mai',
    'june': 'Juin',
    'july': 'Juillet',
    'august': 'Août',
    'september': 'Septembre',
    'october': 'Octobre',
    'november': 'Novembre',
    'december': 'Décembre',
    'capital_pool_desc': 'Valeur totale du business.',
    'cash_capital_desc': 'Liquidités disponibles.',
    'assets_capital_desc': 'Valeur du stock.',
    'stock_deployed_desc': 'Montant total investi en stock.',
    'sales_count_desc': 'Nombre de ventes.',
    'available_profit_desc': 'Profit net retirable.',
    'salary_from_profit_desc': 'Total des prélèvements.',
    'revenue_help': 'Revenu des ventes payées.',
    'stock_cost_help': 'Coût d\'achat inventaire.',
    'business_expenses_help': 'Frais fixes opérationnels.',
    'owner_salary_help': 'Argent retiré du business.',
    'view': 'Voir',
    'please_wait_initial_sync': 'Veuillez patienter pendant la synchronisation initiale...',
  },
};
