import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/language_provider.dart';

String tr(WidgetRef ref, String key) {
  final lang = ref.watch(languageProvider);
  return _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
}

const Map<String, Map<String, String>> _translations = {
  'en': {
    'dashboard': 'Dashboard',
    'catalogs': 'Catalogs',
    'customers': 'Customers',
    'sales': 'Sales',
    'expenses': 'Expenses',
    'finance': 'Finance',
    'financial_health': 'Financial Health',
    'total_revenue': 'Total Revenue',
    'stock_cost': 'Stock Cost',
    'available_profit': 'Available Profit',
    'capital_coverage': 'Capital Coverage',
    'pending_deliveries': 'Pending Deliveries',
    'low_stock_items': 'Low Stock Items',
    'recent_activity': 'Recent Activity',
    'no_activity': 'No activity yet',
    'finance_summary': 'Financial Summary',
    'capital_energy': 'Capital Energy',
    'inject_capital': 'Inject Capital',
    'quick_resume': 'Quick Resume',
    'language': 'Language',
    'settings': 'Settings',
    'online': 'Online',
    'offline_mode': 'Offline Mode',
    'ping_connection': 'Ping Connection',
    'manage_business_data': 'Manage your business data',
    'setup_shop': 'Setting up your shop...',
    'fetching_cloud_data': 'Fetching your data from the cloud',
    'complete': 'Complete!',
    'error': 'Error',
    'retry': 'Retry',
    'dark_mode': 'Dark Mode',
    'logout': 'Logout',
    'welcome_corporate_ladies': 'Welcome to Corporate Ladies',
    'setup_business_profile': 'Let us set up your business profile before you start.',
    'initial_capital': 'Initial Capital (XAF)',
    'start_app': 'Start App',
    'filter': 'Filter:',
    'all': 'All',
    'sales_only': 'Sales Only',
    'expenses_only': 'Expenses Only',
    'english': 'English',
    'french': 'Français',
    'edit': 'Edit',
    'syncing_data': 'Syncing data...',
    'sync_completed': 'Sync completed successfully!',
    'sync_failed': 'Sync failed',
    'success': 'Success',
    'great': 'Great',
    'no_log_file': 'No log file found or it is currently being initialized.',
    'error_sharing_logs': 'Error sharing logs',
    'connection_failed': 'Connection Failed',
    'dismiss': 'Dismiss',
    'confirm_full_reset': 'Confirm Full Reset',
    'cancel': 'Cancel',
    'wipe_data': 'Wipe Data',
    'system_reset_completed': 'System reset completed.',
    'reset_failed': 'Reset failed',
    'new_sale_type': 'New Sale Type',
    'is_this_direct_or_delivery': 'Is this a direct store sale or a delivery?',
    'direct_sale': 'Direct Sale',
    'delivery': 'Delivery',
    'no_discount': 'No Discount',
    'five_percent': '5%',
    'ten_percent': '10%',
    'fifteen_percent': '15%',
    'twenty_percent': '20%',
    'inventory_selection': 'Inventory Selection:',
    'subtotal': 'Subtotal',
    'discount': 'Discount',
    'grand_total': 'Grand Total',
    'confirm_sale': 'Confirm Sale',
    'quick_add_customer': 'Quick Add Customer',
    'save': 'Save',
    'sale_details': 'Sale Details',
    'items': 'Items',
    'confirm_paid': 'Confirm Paid',
    'close': 'Close',
    'update_price_and_stock': 'Update Price and Stock',
    'update': 'Update',
    'exit_app': 'Exit App',
    'are_you_sure_exit': 'Are you sure you want to exit Corporate Ladies?',
    'exit': 'Exit',
    'weekly_checkup': 'Weekly Checkup',
    'stock_deployed': 'Stock Deployed:',
    'recovered_from_sales': 'Recovered from Sales:',
    'remaining_to_recover': 'Remaining to Recover:',
    'capital_injections': 'Capital Injections',
    'capital_injection_details': 'Capital Injection Details',
    'delete': 'Delete',
    'financial_resume': 'Financial Resume',
    'capital_overview': 'Capital Overview',
    'profit_analysis': 'Profit Analysis',
    'expenses_breakdown': 'Expenses Breakdown',
    'this_week_summary': 'This Week\'s Summary',
    'profit_distribution': 'Profit Distribution',
    'payout_reinject_exceed': 'Payout + reinjection cannot exceed available profit',
    'name': 'Name',
    'phone': 'Phone',
    'description': 'Description',
    'notes': 'Notes',
    'optional': 'Optional',
    'price': 'Price',
    'stock_quantity': 'Stock Quantity',
    'required': 'Required',
    'delivery_address': 'Delivery Address',
    'category': 'Category',
    'amount': 'Amount',
    'stock_expense': 'Stock Expense',
    'business_expense': 'Business Expense',
    'personal_payout': 'Personal Payout',
    'select_customer': 'Select Customer',
    'profit_payout': 'Profit Payout (take as salary)',
    'reinject_capital': 'Reinject as Capital',
    'complete_checkup': 'Complete Checkup',
    'add_new_category': 'Add New Category',
    'are_you_sure_delete': 'Are you sure you want to delete',
    'add': 'Add',
    'category_name': 'Category Name',
    'condition_tier': 'Condition Tier',
    'friperie': 'Friperie',
    'boutique': 'Boutique',
    'are_you_sure_delete_customer': 'Are you sure you want to delete',
    'hide_from_active': 'This will hide them from the active list.',
    'registration_success': 'Registration successful! Please check your email.',
    'sign_in': 'Sign In',
    'forgot_password': 'Forgot Password?',
    'development_bypass': 'Development Bypass (Guest Mode)',
    'register': 'Register',
  },
  'fr': {
    'dashboard': 'Tableau de bord',
    'catalogs': 'Catalogues',
    'customers': 'Clients',
    'sales': 'Ventes',
    'expenses': 'Dépenses',
    'finance': 'Finance',
    'financial_health': 'Santé financière',
    'total_revenue': 'Revenu total',
    'stock_cost': 'Coût du stock',
    'available_profit': 'Profit disponible',
    'capital_coverage': 'Couverture du capital',
    'pending_deliveries': 'Livraisons en attente',
    'low_stock_items': 'Stock faible',
    'recent_activity': 'Activité récente',
    'no_activity': 'Aucune activité',
    'finance_summary': 'Résumé financier',
    'capital_energy': 'Énergie du capital',
    'inject_capital': 'Injecter du capital',
    'quick_resume': 'Résumé rapide',
    'language': 'Langue',
    'settings': 'Paramètres',
    'online': 'En ligne',
    'offline_mode': 'Mode hors ligne',
    'ping_connection': 'Vérifier la connexion',
    'manage_business_data': 'Gérer les données de votre business',
    'setup_shop': 'Configuration de votre boutique...',
    'fetching_cloud_data': 'Récupération des données cloud',
    'complete': 'Terminé!',
    'error': 'Erreur',
    'retry': 'Réessayer',
    'dark_mode': 'Mode sombre',
    'logout': 'Se déconnecter',
    'welcome_corporate_ladies': 'Bienvenue chez Corporate Ladies',
    'setup_business_profile': 'Configurons votre profil business avant de commencer.',
    'initial_capital': 'Capital initial (XAF)',
    'start_app': 'Démarrer',
    'filter': 'Filtre:',
    'all': 'Tout',
    'sales_only': 'Ventes seulement',
    'expenses_only': 'Dépenses seulement',
    'english': 'Anglais',
    'french': 'Français',
    'edit': 'Modifier',
    'syncing_data': 'Synchronisation des données...',
    'sync_completed': 'Synchronisation terminée avec succès!',
    'sync_failed': 'Échec de la synchronisation',
    'success': 'Succès',
    'great': 'Super',
    'no_log_file': 'Aucun fichier de journal trouvé ou en cours d\'initialisation.',
    'error_sharing_logs': 'Erreur lors du partage des journaux',
    'connection_failed': 'Échec de la connexion',
    'dismiss': 'Fermer',
    'confirm_full_reset': 'Confirmer la réinitialisation complète',
    'cancel': 'Annuler',
    'wipe_data': 'Effacer les données',
    'system_reset_completed': 'Réinitialisation du système terminée.',
    'reset_failed': 'Échec de la réinitialisation',
    'new_sale_type': 'Nouveau type de vente',
    'is_this_direct_or_delivery': 'Est-ce une vente en magasin ou une livraison?',
    'direct_sale': 'Vente en magasin',
    'delivery': 'Livraison',
    'no_discount': 'Pas de remise',
    'five_percent': '5%',
    'ten_percent': '10%',
    'fifteen_percent': '15%',
    'twenty_percent': '20%',
    'inventory_selection': 'Sélection de l\'inventaire:',
    'subtotal': 'Sous-total',
    'discount': 'Remise',
    'grand_total': 'Total général',
    'confirm_sale': 'Confirmer la vente',
    'quick_add_customer': 'Ajouter rapidement un client',
    'save': 'Enregistrer',
    'sale_details': 'Détails de la vente',
    'items': 'Articles',
    'confirm_paid': 'Confirmer payé',
    'close': 'Fermer',
    'update_price_and_stock': 'Mettre à jour le prix et le stock',
    'update': 'Mettre à jour',
    'exit_app': 'Quitter l\'application',
    'are_you_sure_exit': 'Êtes-vous sûr de vouloir quitter Corporate Ladies?',
    'exit': 'Quitter',
    'weekly_checkup': 'Contrôle hebdomadaire',
    'stock_deployed': 'Stock déployé:',
    'recovered_from_sales': 'Récupéré des ventes:',
    'remaining_to_recover': 'Restant à récupérer:',
    'capital_injections': 'Injections de capital',
    'capital_injection_details': 'Détails de l\'injection de capital',
    'delete': 'Supprimer',
    'financial_resume': 'Résumé financier',
    'capital_overview': 'Aperçu du capital',
    'profit_analysis': 'Analyse du profit',
    'expenses_breakdown': 'Répartition des dépenses',
    'this_week_summary': 'Résumé de la semaine',
    'profit_distribution': 'Distribution du profit',
    'payout_reinject_exceed': 'Le versement + réinjection ne peut pas dépasser le profit disponible',
    'name': 'Nom',
    'phone': 'Téléphone',
    'description': 'Description',
    'notes': 'Notes',
    'optional': 'Optionnel',
    'price': 'Prix',
    'stock_quantity': 'Quantité en stock',
    'required': 'Obligatoire',
    'delivery_address': 'Adresse de livraison',
    'category': 'Catégorie',
    'amount': 'Montant',
    'stock_expense': 'Dépense de stock',
    'business_expense': 'Dépense professionnelle',
    'personal_payout': 'Versement personnel',
    'select_customer': 'Sélectionner un client',
    'profit_payout': 'Versement du profit (comme salaire)',
    'reinject_capital': 'Réinjecter comme capital',
    'complete_checkup': 'Terminer le contrôle',
    'add_new_category': 'Ajouter une nouvelle catégorie',
    'are_you_sure_delete': 'Êtes-vous sûr de vouloir supprimer',
    'add': 'Ajouter',
    'category_name': 'Nom de la catégorie',
    'condition_tier': 'Niveau de condition',
    'friperie': 'Friperie',
    'boutique': 'Boutique',
    'are_you_sure_delete_customer': 'Êtes-vous sûr de vouloir supprimer',
    'hide_from_active': 'Cela les cachera de la liste active.',
    'registration_success': 'Inscription réussie! Veuillez vérifier votre email.',
    'sign_in': 'Se connecter',
    'forgot_password': 'Mot de passe oublié?',
    'development_bypass': 'Contournement de développement (Mode invité)',
    'register': 'S\'inscrire',
  },
};
