import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../providers/language_provider.dart';

String tr(WidgetRef ref, String key) {
  final lang = ref.watch(languageProvider);
  return _translations[lang]?[key] ?? _translations['en']?[key] ?? key;
}

const Map<String, Map<String, String>> _translations = {
  'en': {
    'dashboard': 'Dashboard',
    'catalogs': 'Catalogs',
    'customers': 'Customers',
    'sales': 'Sales',
    'expenses': 'Expenses',
    'finance': 'Finance',
    'financial_health': 'Financial Health',
    'total_revenue': 'Total Revenue',
    'stock_cost': 'Stock Cost',
    'available_profit': 'Available Profit',
    'capital_coverage': 'Capital Coverage',
    'pending_deliveries': 'Pending Deliveries',
    'low_stock_items': 'Low Stock Items',
    'recent_activity': 'Recent Activity',
    'no_activity': 'No activity yet',
    'finance_summary': 'Financial Summary',
    'capital_energy': 'Capital Energy',
    'inject_capital': 'Inject Capital',
    'quick_resume': 'Quick Resume',
    'language': 'Language',
    'settings': 'Settings',
    'online': 'Online',
    'offline_mode': 'Offline Mode',
    'ping_connection': 'Ping Connection',
    'manage_business_data': 'Manage your business data',
    'setup_shop': 'Setting up your shop...',
    'fetching_cloud_data': 'Fetching your data from the cloud',
    'complete': 'Complete!',
    'error': 'Error',
    'retry': 'Retry',
    'dark_mode': 'Dark Mode',
    'logout': 'Logout',
    'welcome_corporate_ladies': 'Welcome to Corporate Ladies',
    'setup_business_profile': 'Let us set up your business profile before you start.',
    'initial_capital': 'Initial Capital (XAF)',
    'start_app': 'Start App',
  },
  'fr': {
    'dashboard': 'Tableau de bord',
    'catalogs': 'Catalogues',
    'customers': 'Clients',
    'sales': 'Ventes',
    'expenses': 'Dépenses',
    'finance': 'Finance',
    'financial_health': 'Santé financière',
    'total_revenue': 'Revenu total',
    'stock_cost': 'Coût du stock',
    'available_profit': 'Profit disponible',
    'capital_coverage': 'Couverture du capital',
    'pending_deliveries': 'Livraisons en attente',
    'low_stock_items': 'Stock faible',
    'recent_activity': 'Activité récente',
    'no_activity': 'Aucune activité',
    'finance_summary': 'Résumé financier',
    'capital_energy': 'Énergie du capital',
    'inject_capital': 'Injecter du capital',
    'quick_resume': 'Résumé rapide',
    'language': 'Langue',
    'settings': 'Paramètres',
    'online': 'En ligne',
    'offline_mode': 'Mode hors ligne',
    'ping_connection': 'Vérifier la connexion',
    'manage_business_data': 'Gérer les données de votre business',
    'setup_shop': 'Configuration de votre boutique...',
    'fetching_cloud_data': 'Récupération des données cloud',
    'complete': 'Terminé!',
    'error': 'Erreur',
    'retry': 'Réessayer',
    'dark_mode': 'Mode sombre',
    'logout': 'Se déconnecter',
    'welcome_corporate_ladies': 'Bienvenue chez Corporate Ladies',
    'setup_business_profile': 'Configurons votre profil business avant de commencer.',
    'initial_capital': 'Capital initial (XAF)',
    'start_app': 'Démarrer',
  },
};
